### PR TITLE
Clarify that every message should have a unique GUID.

### PR DESCRIPTION
**Pull request by otterdahl**
- Clarify that every message should have a unique GUID.
- Move some content from table in order to make it easier to read in the online view

### CODE REVIEW

**Comment by marcgarba** [comment]
Nice clarification and reorganization.
a little typo: "**mId** is used **i** all messages as a reference for the message ack" => "in".

**Comment by otterdahl** [comment]
> a little typo: "**mId** is used **i** all messages as a reference for the message ack" => "in".

Fixed

**Comment by emiltin** [comment]
Let's be even more clear and state that even if you resend the same messages again, it should have a new GUID.

**Comment by otterdahl** [comment]
> Let's be even more clear and state that even if you resend the same messages again, it should have a new GUID.

The PR has been updated. Merging this

**Pull request merged**
