### PR TITLE
RSMP 3.2.2

### PR DESCRIPTION
**Pull request by otterdahl**
- [x] #131  
- [x] #134
- [x] #136
- [x] #149
- [x] #137
- [x] #138
- [x] #155
- [x] #156
- [x] #157
- [x] #159 
- [x] #160
- [x] #162
- [x] #164
- [x] Update changelog

### CODE REVIEW

**Comment by emiltin** [comment]
The schema, rsmp gem and validator has been updated and not support core 3.2.2, and also tcl sxl 1.2.1
- the tlc emulator now runs core 3.2.2, tlc sxl 1.2.1
- connect_spec.rb now includes a test for core 3.2.2, but note that still will only run if the test config specifies 3.2.2 for the equipment (itc-3 still uses an older version)

**Comment by otterdahl** [comment]
No, they´re not required

**Comment by emiltin** [comment]
Anything left to do?

**Comment by otterdahl** [comment]
I don't think so. I can update the release date in the changelog and release both core and sxl today if it's ok with you.

**Comment by emiltin** [comment]
Time for an announcement at https://github.com/orgs/rsmp-nordic/discussions/new?category=announcements?

**Comment by otterdahl** [comment]
Fixed. Added an announcement

**Pull request merged**
